### ISSUE TITLE
Reset and power cycle with qpair remaining

### ISSUE THREAD

**Issue by catogts** [pynvme/pynvme#47]
Hi Crane. some suggestion about process qpair

When the iowoker is running, the power cycle and reset are working well, so I'm doing a good test.

However, there is a problem that the test is stuck in the pending state at the moment when the qpair remains, and it does not proceed.

It is also necessary to forcibly discard the qpair during a reset and power cycle with the qpair remaining.

Many abnormal behaviors do not always appear to be accompanied by delete qpair operations.

thank you

**Comment by cranechu** [comment]
Hi, Catogts, 

Yes, that is an issue working in progress. In dirty power off, we have to shut the power off before closing iowoker, in order to create a real dirty power off test scenario. However, when ioworker try to close its qpair, the drive is offline, so cannot response any command, like delete SQ/CQ, and then many abnormal behaviors could happen, as you mentioned above. 

It is just an experimental feature, and not fully tested in the up coming release. We are working on it to make the dirty power off more smooth and reliable. 

Thanks, 
-Crane
