### ISSUE TITLE
Question about d.crc32_unlock_all in driver_cleanup

### ISSUE THREAD

**Issue by catogts** [pynvme/pynvme#58]
Hi Crane

Significant delays are found when testing power cycles on servers with large amounts of memory.  

After checking the log in driver_wrap, d.crc32_unlock_all has a delay of about 20 seconds.  

On desktop pc testing the same nvme device, only a delay of 1 to 2 seconds occurs, but it takes a long time on a server with a large amount of memory. 

 So, I am skipping d.crc32_unlock_all right now, and what is d.crc32_unlock_all doing?

**Comment by cranechu** [comment]
Hi, CaTo, 

Please refer to this: https://pynvme.readthedocs.io/features.html#data-verify
The locker is used to avoid LBA confliction and make data verify possible in single ioworker. 
One tradeoff method is to reduce the verify scope in Namespace init, like, 
```python
nvme0n1 = d.Namespace(nvme0, 1, 1000)
```
Then, only LBA 0-999 have their CRC and locker.

Moreover, It may introduce a long delay, however, it has no impact of power off test, because it happens after power off, and before power on.
