### ISSUE TITLE
using shutdown_notify during ioworker

### ISSUE THREAD

**Issue by catogts** [pynvme/pynvme#66]
hi crane

i see subsystem.shutdown_notify() cant stop iowoker

if i send shutdown_notify during iowoker then occur csts.shst timeout

how about putting ioworker terminate function in shutdown_notify?

i try to modify driver_wrap.pyx add cleanup_driver in shutdown_notify

but sometimes(multi device testing) failed with ioworker_one_cb

thank you

**Comment by cranechu** [comment]
Hi, Catogts, 

Sending shtudown_notify in active ioworker, and got csts.shst timeout. I think the timeout is correct, because device cannot shutdown when handling IO. So, it is a meaningful test to check if the device properly handle the non-proper shutdown notification. 

Can you move shutdown_notify outside of ioworkers in your script? 

Thanks, 
-Crane
