### ISSUE TITLE
question about secondary process not cleared

### ISSUE THREAD

**Issue by catogts** [pynvme/pynvme#99]
hi crane

i have some problem about secondary process not cleared

Sometimes, when power cycle or reset during ioworker, secondary process is not cleared and fails. 

It is assumed that the ioworker process is abnormally terminated and there is no process. In this case, is there any way to solve it?

And is there any way to deal with the abnormal termination of ioworker?

thank you

**Comment by cranechu** [comment]
Hi, Catogts, 

When ioworker is terminated due to async power cycle or reset, we can handle it to close ioworker, as well as the secondary process immediately. If you have the test log that secondary process is not cleared, could you please share it with us for further investigation? 

Thanks, 
-Crane

**Comment by cranechu** [comment]
Also, you can try PyNVMe3: http://pynv.me/3/
